Manifest v2

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -12,30 +12,30 @@ source /usr/share/yunohost/helpers
 #=================================================
 # LOAD SETTINGS
 #=================================================
-ynh_script_progression --message="Loading installation settings..."
+#REMOVEME? ynh_script_progression --message="Loading installation settings..."
 
-app=$YNH_APP_INSTANCE_NAME
+#REMOVEME? app=$YNH_APP_INSTANCE_NAME
 
-domain=$(ynh_app_setting_get --app=$app --key=domain)
-path_url=$(ynh_app_setting_get --app=$app --key=path)
-admin=$(ynh_app_setting_get --app=$app --key=admin)
-final_path=$(ynh_app_setting_get --app=$app --key=final_path)
-db_name=$(ynh_app_setting_get --app=$app --key=db_name)
-db_user=$db_name
-db_pwd=$(ynh_app_setting_get --app=$app --key=mysqlpwd)
-password=$(ynh_app_setting_get --app=$app --key=password)
-master_key=$(ynh_app_setting_get --app=$app --key=master_key)
+#REMOVEME? domain=$(ynh_app_setting_get --app=$app --key=domain)
+#REMOVEME? path=$(ynh_app_setting_get --app=$app --key=path)
+#REMOVEME? admin=$(ynh_app_setting_get --app=$app --key=admin)
+#REMOVEME? #REMOVEME? install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
+#REMOVEME? db_name=$(ynh_app_setting_get --app=$app --key=db_name)
+#REMOVEME? db_user=$db_name
+#REMOVEME? db_pwd=$(ynh_app_setting_get --app=$app --key=mysqlpwd)
+#REMOVEME? password=$(ynh_app_setting_get --app=$app --key=password)
+#REMOVEME? master_key=$(ynh_app_setting_get --app=$app --key=master_key)
 
-blog_admin=$(ynh_app_setting_get --app=$app --key=blog_admin)
-blog_contentadmin=$(ynh_app_setting_get --app=$app --key=blog_contentadmin)
-blog_usage=$(ynh_app_setting_get --app=$app --key=blog_usage)
-blog_publish=$(ynh_app_setting_get --app=$app --key=blog_publish)
-blog_delete=$(ynh_app_setting_get --app=$app --key=blog_delete)
-blog_categories=$(ynh_app_setting_get --app=$app --key=blog_categories)
-blog_media_admin=$(ynh_app_setting_get --app=$app --key=blog_media_admin)
-blog_media=$(ynh_app_setting_get --app=$app --key=blog_media)
-blog_pages=$(ynh_app_setting_get --app=$app --key=blog_pages)
-blog_blogroll=$(ynh_app_setting_get --app=$app --key=blog_blogroll)
+#REMOVEME? blog_admin=$(ynh_app_setting_get --app=$app --key=blog_admin)
+#REMOVEME? blog_contentadmin=$(ynh_app_setting_get --app=$app --key=blog_contentadmin)
+#REMOVEME? blog_usage=$(ynh_app_setting_get --app=$app --key=blog_usage)
+#REMOVEME? blog_publish=$(ynh_app_setting_get --app=$app --key=blog_publish)
+#REMOVEME? blog_delete=$(ynh_app_setting_get --app=$app --key=blog_delete)
+#REMOVEME? blog_categories=$(ynh_app_setting_get --app=$app --key=blog_categories)
+#REMOVEME? blog_media_admin=$(ynh_app_setting_get --app=$app --key=blog_media_admin)
+#REMOVEME? blog_media=$(ynh_app_setting_get --app=$app --key=blog_media)
+#REMOVEME? blog_pages=$(ynh_app_setting_get --app=$app --key=blog_pages)
+#REMOVEME? blog_blogroll=$(ynh_app_setting_get --app=$app --key=blog_blogroll)
 
 #=================================================
 # CHECK VERSION
@@ -47,16 +47,16 @@ upgrade_type=$(ynh_check_app_version_changed)
 #=================================================
 # BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
 #=================================================
-ynh_script_progression --message="Backing up the app before upgrading (may take a while)..." --weight=4
+#REMOVEME? ynh_script_progression --message="Backing up the app before upgrading (may take a while)..." --weight=4
 
 # Backup the current version of the app
-ynh_backup_before_upgrade
-ynh_clean_setup () {
+#REMOVEME? ynh_backup_before_upgrade
+#REMOVEME? ynh_clean_setup () {
 	# Restore it if the upgrade fails
-	ynh_restore_upgradebackup
+#REMOVEME? 	ynh_restore_upgradebackup
 }
 # Exit if an error occurs during the execution of the script
-ynh_abort_if_errors
+#REMOVEME? ynh_abort_if_errors
 
 #=================================================
 # STANDARD UPGRADE STEPS
@@ -68,16 +68,16 @@ ynh_script_progression --message="Ensuring downward compatibility..."
 # If db_name doesn't exist, create it
 if [ -z "$db_name" ]; then
 	db_name=$(ynh_sanitize_dbid --db_name=$app)
-	ynh_app_setting_set --app=$app --key=db_name --value=$db_name
+#REMOVEME? 	ynh_app_setting_set --app=$app --key=db_name --value=$db_name
 fi
 
-# If final_path doesn't exist, create it
-if [ -z "$final_path" ]; then
-	final_path=/var/www/$app
-	ynh_app_setting_set --app=$app --key=final_path --value=$final_path
+# If install_dir doesn't exist, create it
+if [ -z "$install_dir" ]; then
+#REMOVEME? 	install_dir=/var/www/$app
+#REMOVEME? 	ynh_app_setting_set --app=$app --key=install_dir --value=$install_dir
 fi
 
-if [ -n "$(ynh_app_setting_get --app=$app --key=is_public)" ]; then
+#REMOVEME? if [ -n "$(ynh_app_setting_get --app=$app --key=is_public)" ]; then
 	ynh_app_setting_delete --app=$app --key=protected_uris
 
 	# Removing skipped/unprotected_uris under certain conditions, remove the visitors group added during the migration process of 3.7
@@ -85,16 +85,16 @@ if [ -n "$(ynh_app_setting_get --app=$app --key=is_public)" ]; then
 	if ynh_permission_has_user --permission=main --user=visitors
 	then
 		ynh_app_setting_delete --app=$app --key=unprotected_uris
-		ynh_permission_update --permission "main" --add "visitors"
+#REMOVEME? 		ynh_permission_update --permission "main" --add "visitors"
 	else
 		ynh_app_setting_delete --app=$app --key=unprotected_uris
 	fi
 	ynh_app_setting_delete --app=$app --key=is_public
 fi
 
-if ! ynh_permission_exists --permission="admin"; then
+#REMOVEME? if ! ynh_permission_exists --permission="admin"; then
 	# Create the required permissions
-	ynh_permission_create --permission="admin" --url="/admin" --allowed=$admin
+#REMOVEME? 	ynh_permission_create --permission="admin" --url="/admin" --allowed=$admin
 fi
 
 if [ -z "$blog_admin" ] ||
@@ -117,13 +117,13 @@ if [ -z "$blog_admin" ] ||
 	blog_media="false"
 	blog_pages="false"
 	blog_blogroll="false"
-	ynh_app_setting_set --app=$app --key=blog_admin --value=$blog_admin
-	ynh_app_setting_set --app=$app --key=blog_contentadmin --value=$blog_contentadmin
+#REMOVEME? 	ynh_app_setting_set --app=$app --key=blog_admin --value=$blog_admin
+#REMOVEME? 	ynh_app_setting_set --app=$app --key=blog_contentadmin --value=$blog_contentadmin
 	ynh_app_setting_set --app=$app --key=blog_usage --value=$blog_usage
 	ynh_app_setting_set --app=$app --key=blog_publish --value=$blog_publish
 	ynh_app_setting_set --app=$app --key=blog_delete --value=$blog_delete
 	ynh_app_setting_set --app=$app --key=blog_categories --value=$blog_categories
-	ynh_app_setting_set --app=$app --key=blog_media_admin --value=$blog_media_admin
+#REMOVEME? 	ynh_app_setting_set --app=$app --key=blog_media_admin --value=$blog_media_admin
 	ynh_app_setting_set --app=$app --key=blog_media --value=$blog_media
 	ynh_app_setting_set --app=$app --key=blog_pages --value=$blog_pages
 	ynh_app_setting_set --app=$app --key=blog_blogroll --value=$blog_blogroll
@@ -132,10 +132,10 @@ fi
 #=================================================
 # CREATE DEDICATED USER
 #=================================================
-ynh_script_progression --message="Making sure dedicated system user exists..."
+#REMOVEME? ynh_script_progression --message="Making sure dedicated system user exists..."
 
 # Create a dedicated user (if not existing)
-ynh_system_user_create --username=$app --home_dir=$final_path
+#REMOVEME? ynh_system_user_create --username=$app --home_dir=$install_dir
 
 #=================================================
 # DOWNLOAD, CHECK AND UNPACK SOURCE
@@ -152,16 +152,16 @@ then
 	ynh_script_progression --message="Upgrading source files..."
 
 	# Download, check integrity, uncompress and patch the source from app.src
-	ynh_setup_source --dest_dir="$final_path"
+	ynh_setup_source --dest_dir="$install_dir"
 fi
 
-chmod 750 "$final_path"
-chmod -R o-rwx "$final_path"
-chown -R $app:www-data "$final_path"
+chmod 750 "$install_dir"
+chmod -R o-rwx "$install_dir"
+chown -R $app:www-data "$install_dir"
 
 # https://dotclear.org/documentation/2.0/admin/install
-mkdir -p "$final_path/"{cache,public}
-setfacl -m d:u:www-data:rwx "$final_path/"{cache,public}
+mkdir -p "$install_dir/"{cache,public}
+setfacl -m d:u:www-data:rwx "$install_dir/"{cache,public}
 
 #=================================================
 # NGINX CONFIGURATION
@@ -186,13 +186,13 @@ ynh_add_fpm_config
 #=================================================
 ynh_script_progression --message="Updating a configuration file..."
 
-php_config=$final_path/inc/config.php
+php_config=$install_dir/inc/config.php
 
 ynh_backup_if_checksum_is_different --file=$php_config
 
 cp $php_config.in $php_config
 
-admin_url="${path_url%/}/admin/"
+admin_url="${path%/}/admin/"
 
 email=$(ynh_user_get_info --username=$admin --key=mail)
 
@@ -207,7 +207,7 @@ ynh_replace_string --match_string="'DC_ADMIN_URL', ''" --replace_string="'DC_ADM
 ynh_replace_string --match_string="'DC_ADMIN_MAILFROM', ''" --replace_string="'DC_ADMIN_MAILFROM', '$email'" --target_file=$php_config
 
 # Adding LDAP login
-ynh_add_config --template="../conf/class.auth.ldap.php" --destination="$final_path/inc/class.auth.ldap.php"
+ynh_add_config --template="../conf/class.auth.ldap.php" --destination="$install_dir/inc/class.auth.ldap.php"
 
 cat << EOF >> $php_config
 
@@ -237,14 +237,14 @@ ynh_local_curl $adminUrl
 ynh_script_progression --message="Reconfiguring Fail2Ban..."
 
 # Create a dedicated Fail2Ban config
-ynh_add_fail2ban_config --logpath="/var/log/nginx/${domain}-error.log" --failregex="Invalid credentials in $final_path/inc/class.auth.ldap.php .* client: <HOST>, .*https://$domain${path_url%/}/admin/auth.php"
+ynh_add_fail2ban_config --logpath="/var/log/nginx/${domain}-error.log" --failregex="Invalid credentials in $install_dir/inc/class.auth.ldap.php .* client: <HOST>, .*https://$domain${path%/}/admin/auth.php"
 
 #=================================================
 # RELOAD NGINX
 #=================================================
-ynh_script_progression --message="Reloading NGINX web server and PHP-FRM..."
+#REMOVEME? ynh_script_progression --message="Reloading NGINX web server and PHP-FRM..."
 
-ynh_systemd_action --service_name=nginx --action=reload
+#REMOVEME? ynh_systemd_action --service_name=nginx --action=reload
 ynh_systemd_action --service_name=php$YNH_PHP_VERSION-fpm --action=reload
 
 #=================================================
